apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::356782802290:user/udacity
      username: jenkins
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::356782802290:role/UdacityCapStone-K8S-Workers-NodeInstanceRole-6LW3P7YAVFQU	
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes