apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-sample-app
  labels:
    app: capstone-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-sample-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-sample-app
    spec:
      containers:
        - name: devops-capstone
          image: omarmerghany/app
          ports:
            - containerPort: 80
