apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::356782802290:user/Temp_User_For_Learning
      username: Temp_User_For_Learning
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::356782802290:role/UdacityCapStone-K8S-Workers-NodeInstanceRole-1XWPRTF7RB23S
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
